[package]
name = "gitsnap-desktop"
version = "0.1.0"
description = "GitSnap desktop (Streamlit in finestra Tauri)"
edition = "2021"

[lib]
name = "gitsnap_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
